[theme]
base = "dark"
backgroundColor = "#0a0a0a"
secondaryBackgroundColor = "#1a1a1a"
textColor = "#ffffff"
primaryColor = "#1f77b4"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
headless = true
